config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :companies
  root 'articles#index'
  resources :birt_test
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :industry
  belongs_to :nature
  belongs_to :scale
  has_and_belongs_to_many :tags, join_table: "taggings"
  
  def get_tags
    arr = []
    self.tags.each do |tag|
      arr << tag.name
    end
    arr
  end
end

app/models/industry.rb
class Industry < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_and_belongs_to_many :tags#, :association_foreign_key => "tags_id"
  has_one :member_avatar
  has_one :member_detail
  has_one :member_info
  has_one :member_monologue

end

app/models/member_avatar.rb
class MemberAvatar < ActiveRecord::Base
  validates :member_id, presence: true, uniqueness: false
  belongs_to :member

end

app/models/member_detail.rb
class MemberDetail < ActiveRecord::Base
  validates :member_id, presence: true, uniqueness: false
  belongs_to :member

end

app/models/member_info.rb
class MemberInfo < ActiveRecord::Base
  belongs_to :member
  has_one :avatar, class_name:'MemberAvatar',primary_key: 'member_id',foreign_key: 'member_id'

  validates :member_id, presence: true, uniqueness: true

end

app/models/member_monologue.rb
class MemberMonologue < ActiveRecord::Base
  validates :member_id, presence: true, uniqueness: false
  belongs_to :member
end

app/models/nature.rb
class Nature < ActiveRecord::Base
end

app/models/redis_client.rb
module RedisClient
  module_function
  def config
    {:host=>'localhost', :port=>6379, :password=>'sun', :db => 0}
  end

  def client
    @redis||=Redis.new(config)
  end
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :children, class_name: "Region",foreign_key: "parent_id"
  belongs_to :parent, class_name: "Region"

end

app/models/scale.rb
class Scale < ActiveRecord::Base
end

app/models/setting.rb
class Setting < Settingslogic
  source "#{Rails.root}/config/settings.yml"
  namespace Rails.env
end

app/models/tag.rb
class Tag < ActiveRecord::Base

end

app/models/tag_type.rb
class TagType < ActiveRecord::Base
  validates :name, presence: true
  has_many :tags, dependent: :destroy
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
end

app/models/test_bcrypt.rb
require 'bcrypt'

my_password1 = BCrypt::Password.create("aaaaaa")
my_password2 = BCrypt::Password.create("aaaaaa")
my_password3 = BCrypt::Password.create("aaaaaa")
puts my_password1
puts my_password2
puts my_password3
puts my_password1 == "aaaaaa"
my_password = BCrypt::Password.new("$2a$10$h4PqD8GwY5gmhurMuEFrzebCQ6i4HHaTFVvkBIR0hfXguxyGGpR4e")
puts my_password == "12345678"

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
    @articles = @articles.page(params[:page]).per(params[:per])
  end
  def show
    @article = Article.find(params[:id])
    @article.update_attribute(:read_num, @article.read_num + 1)
    code_entity = HTMLEntities.new
    @content = code_entity.decode(@article.content)
  end
end

app/controllers/birt_test_controller.rb
class BirtTestController < ApplicationController
  def index
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
    @companies = @companies.page(params[:page]).per(params[:per])
  end
  def show
    @company = Company.find(params[:id])
    code_entity = HTMLEntities.new
    @content = code_entity.decode(@company.detail_introduce)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/companies/index.html.haml
.container
  %table.table.table-striped
    %thead
      %tr
        %th 公司名
        %th 所属行业
        %th 公司性质
        %th 公司规模
        %th 邮编
        %th 网址
        %th 详情
        %th 地址
        %th tags
        %th=t '.actions', :default => t("helpers.actions")
  
    - @companies.each do |item|
      %tr
        %td= item.name
        %td= item.industry.name if item.industry
        %td= item.nature.name if item.nature
        %td= item.scale.name if item.scale
        %td= item.zip_code
        %td= item.website
        %td
          = link_to '详情', "#{item.detail_info_url}", :target => '_blank'
        %td= item.address
        %th
          - item.get_tags.each do |tag|
            %span.label.label-default= tag
        %td
          = link_to 'show', company_path(item), :class => 'btn btn-mini'
  = paginate @companies

app/views/companies/show.html.haml
%div.container
  %h2.text-center
    = @company.name
  %h4.text-right
    %br
    阅读次数:
    = @company.zip_code
  = raw(@content)